Instagram/urls.py
from django.contrib import admin
from django.urls import path,include
import appname.views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', appname.views.main, name='main'),
    path('create/', appname.views.create, name='create'),
    path('update/<int:pk>', appname.views.update, name='update'),
    path('delete/<int:pk>', appname.views.delete, name='delete'),
    path('signin', appname.views.signin, name='signin'),
    path('signup/', appname.views.signup, name='signup'),
    path('mypage/', appname.views.mypage, name='mypage'),
    path('kakao_map/<int:post_id>', appname.views.kakao_map, name='kakao_map'),
    # path('search', appname.views.search, name='search'),
    path('', include('django.contrib.auth.urls')),
    path('comment/<int:post_id>', appname.views.comment, name='comment'),
    path('hashtag/<str:hashtag_name>',appname.views.hashtag,name='hashtag'),
    path('like/', appname.views.post_like,name='post_like'),
    path('',include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

appname/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from datetime import datetime
# Create your models here.

class Post(models.Model):
    def __str__(self):
        return self.title
    title = models.CharField(max_length=200)
    content = models.TextField()
    image = models.ImageField(upload_to='images/', blank=True)
    writer = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="writer", default="")
    
    hashtag_field = models.CharField(max_length=200, blank=True)
    hashtags = models.ManyToManyField('Hashtag', blank=True)
    restaurant_location = models.CharField(max_length=200,blank=True)
    create_date = models.DateTimeField('date published',blank=True ,default=datetime.now())#게시물 등록후 지난 시간을 나타내는 필드
    

    like_user_set = models.ManyToManyField(
        settings.AUTH_USER_MODEL, blank=True, related_name="like_user_set", through="Like")

    @property
    def like_count(self):
        return self.like_user_set.count()


class Like(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    class Meta:
        unique_together = (
            ('user', 'post')
        )


class Hashtag(models.Model):
    def __str__(self):
        return self.related_name

    name = models.CharField(max_length=50)


class CustomUser(AbstractUser):
    def __str__(self):
        return self.username
    
    nickname = models.CharField(max_length=20)
    phone_number = models.CharField(max_length=20)
    profileimage = models.ImageField(upload_to='images/', blank=True)

class Comment(models.Model):
    def __str__(self):
        return self.text
    c_writer = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="c_writer", default="")
    post_id = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='comments')
    text = models.CharField(max_length=50)
    class Meta:
        ordering = ['-id']
            
    def __str__(self):
        return '%s - %s' % (self.c_writer, self.text) 

appname/forms.py
from django import forms
from .models import Post, CustomUser, Comment, Hashtag
# from django.contrib.auth.models import User


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'image', 'hashtag_field','restaurant_location']


class SigninForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'password']
        help_texts = {
            'username': None,
        }


class UserForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'password', 'nickname', 'phone_number' ,'profileimage']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']


class HashtagForm(forms.ModelForm):
    class Meta:
        model = Hashtag
        fields = ['name']

appname/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post, CustomUser, Hashtag
from .forms import PostForm, SigninForm, UserForm, CommentForm, HashtagForm
from django.template.loader import render_to_string
# from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate
from django.http import HttpResponse, JsonResponse
import json
from django.utils import timezone
from datetime import datetime
from django.core.paginator import Paginator

# Create your views here.


def main(request):
    posts = Post.objects.all().order_by('-id')
    # users = User.objects.all()
    signin_form = SigninForm()
    comment_form = CommentForm()
    userList =CustomUser.objects.all().order_by('-id')
    paginator = Paginator(userList,5)
    page = request.GET.get('page')
    pages =  paginator.get_page(page)
    return render(request, 'appname/main.html', {'posts': posts,'userList':userList,'pages':pages, 'signin_form': signin_form, 'comment_form': comment_form})


def create(request):
    if not request.user.is_active:
        return HttpResponse("Can't write a post without Sign In")

    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.writer = request.user
            post.create_date = timezone.datetime.now()
            hashtag_field = form.cleaned_data['hashtag_field']
            restaurant_location = form.cleaned_data['restaurant_location']
            str_hashtags = hashtag_field.split('#')
            list_hashtags = list()

            for hashtag in str_hashtags:
                if Hashtag.objects.filter(name=hashtag):
                    list_hashtags.append(Hashtag.objects.get(name=hashtag))
                else:
                    temp_hashtag = HashtagForm().save(commit=False)
                    temp_hashtag.name = hashtag
                    temp_hashtag.save()
                    list_hashtags.append(temp_hashtag)

            post.save()
            post.hashtags.add(*list_hashtags)
            return redirect('main')
    else:
        form = PostForm()
        return render(request, 'appname/create.html', {'form': form})


def read(request):
    return redirect('main')


def update(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form = form.save(commit=False)
            form.save()
            return redirect('main')
    else:
        form = PostForm(instance=post)
        return render(request, 'appname/create.html', {'form': form})


def delete(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return redirect('main')


def signin(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('main')
        else:
            return HttpResponse("로그인 실패. 다시 시도해보세요")
    else:
        signin_form = SigninForm()
        return render(request, 'appname/signin.html', {'signin_form': signin_form})


def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            new_user = CustomUser.objects.create_user(username=form.cleaned_data['username'],
                                                      email=form.cleaned_data['email'],
                                                      password=form.cleaned_data['password'],
                                                      nickname=form.cleaned_data['nickname'],
                                                      phone_number=form.cleaned_data['phone_number'],
                                                      profileimage=request.FILES['profileimage'])
            login(request, new_user)
            return redirect('main')
    else:
        form = UserForm()
        return render(request, 'appname/signup.html', {'form': form})


def hashtag(request, hashtag_name):
    hashtag = get_object_or_404(Hashtag, name=hashtag_name)
    return render(request, 'appname/hashtag.html', {'hashtag': hashtag})


def mypage(request):
    posts = Post.objects.all().order_by('-id')
    signin_form = SigninForm()
    comment_form = CommentForm()
    return render(request, 'appname/mypage.html', {'posts': posts, 'signin_form': signin_form, 'comment_form': comment_form})


def post_like(request):
    pk = request.POST.get('pk', None)  # ajax 통신을 통해서 template에서 POST방식으로 전달
    post = get_object_or_404(Post, pk=pk)
    post_like, post_like_created = post.like_set.get_or_create(
        user=request.user)

    if not post_like_created:
        post_like.delete()
        message = "좋아요 취소"
    else:
        message = "좋아요"

    context = {'like_count': post.like_count,
               'message': message
               }

    return HttpResponse(json.dumps(context), content_type="application/json")
    # context를 json 타입으로


def post_list(request):
    posts = Post.objects.all()
    return render(request, 'appname/main.html', {'object_list': posts})


def comment(request, post_id):
    if not request.user.is_active:
        return HttpResponse("Can't write a comment without Sign In")
    post = get_object_or_404(Post, id=post_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.c_writer = request.user
            comment.post_id = post
            comment.text = form.cleaned_data['text']
            comment.save()
            return redirect('main')


def kakao_map(request, post_id):
    post = get_object_or_404(Post, id=post_id)

    return render(request, 'appname/kakao_map.html', {'post': post})

appname/templates/appname/base.html
<!doctype html>
{% load static %}

<html>

<head>
<style>
   @font-face {
    font-family: 'TmoneyRoundWindExtraBold';
    src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_20-07@1.0/TmoneyRoundWindExtraBold.woff') format('woff');
    font-weight: normal;
    font-style: normal;
}

</style>
  
  <!-- Bootstrap core CSS -->
  
  <meta http-equiv="content-type" content="text/html; charset=UTF-8"> 
  <meta charset="utf-8">
  <title>진형준 인스타그램</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

  <!--[if lt IE 9]>
    <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
 <!-- 합쳐지고 최소화된 최신 CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>

<body style="font-family: TmoneyRoundWindExtraBold ;">
  <nav class="navbar  fixed-top navbar-expand-lg navbar-dark  " style="background-color: blueviolet; ">
    
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent" >
      <ul class="navbar-nav mr-auto" style="width: 80%;">
        <li class="nav-item active">
          <a class="nav-link  fab fa-instagram" href="{% url 'main' %}" style="font-size: medium;">Instagram </a>
        </li>
        <li class="nav-item">
          <a class="nav-link glyphicon glyphicon-plus" href="{% url 'create' %}" style="font-size:medium;" ></a>
        </li>
      
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle glyphicon glyphicon-user" href="#" style="font-size:medium;" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="background-color:  rgb(118, 98, 209);">
            {% if user.is_authenticated %}     
            <a  class="dropdown-item" href="{% url 'logout' %}" style="font-size: medium; ">Logout</a>
            <a  class="dropdown-item" href="{% url 'mypage' %}" style="font-size: medium;  ">Mypage</a>
          {% else %}
            <a  class="dropdown-item" href="{% url 'signin' %}" style="font-size: medium;  ">Login</a>
           <a class="dropdown-item" href="{% url 'signup' %}" style="font-size: medium;  ">Signup</a>
          {% endif %}
          </div>
          
        </li>
       
      </ul>
  
      <form class="form-inline my-4 my-lg-2" style="width: 100%;">
        <input class="form-control mr-sm-3" type="search" placeholder="Search" aria-label="Search">
        <button class="btn  my-2 my-sm-0" type="submit" style="font-weight: bold; background-color: coral;">Search</button>
      </form>
    </div>
  
  </nav>
      
{% block header %}
{% endblock %}
  
  {% block content %}
  {% endblock %}

  <!-- Footer -->
  <footer class="container-fluid navbar-fixed-bottom int-footer" class="int-footer" style="background-color: blueviolet; ">
    <div class="container">
      <p class="m-0 text-center text-white medium">Likelion &copy; JHJ Instagram 2020</p>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
   <script src="{% static 'appname/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'appname/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'appname/js/jquery.js' %}"></script>
  <script type="text/javascript" src="{% static 'appname/js/bootstrap.js' %}"></script>
</body>

</html>

appname/templates/appname/create.html
{% extends 'appname/base.html' %}
{% load crispy_forms_tags %}
{% block header %}

{%  endblock %}
{% block content %}
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<div class="col-4">
<form method="POST" enctype="multipart/form-data" style="font-size:large;">
  {% csrf_token %}
  <table>
    {{ form|crispy}}
  </table>
  <input type="submit" value="submit" class="btn btn-info"> //django crispy_form사용
</form>
</div>
{% endblock %}

appname/templates/appname/hashtag.html
{% extends 'appname/base.html' %}

{% block header %}
<header class="masthead text-center text-white">
    <div class="masthead-content">
      <div class="container">
        <h1 class="masthead-heading mb-0">{{ hashtag.name }}</h1>
       
        <h2 class="masthead-subheading mb-0">hello </h2>
      </div>
    </div>
    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div>
    <div class="bg-circle-4 bg-circle"></div>
  </header>
{% endblock %}

{% block content %}
{% for post in hashtag.post_set.all %}
<section>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6 order-lg-2">
        <div class="p-5">
          {% if post.image %}
          <img class="img-fluid rounded-circle" src="{{ post.image.url }}" alt="" width="200">
          {% endif %}
        </div>
      </div>
      
      <div class="col-lg-6 order-lg-1">
        <div class="p-5">
          <h4 class="display-6">작성자 : {{ post.writer}}</h4>
          <h2 class="display-4">제목 : {{post.title}}</h2>
          <p>{{post.content}}</p>

          <span>
            {% for hashtag in post.hashtags.all %}
              {{ hashtag.name }}
            {% endfor %}
          </span>
          <br>
          <a href="{% url 'update' pk=post.pk %}"> 수정하기 </a>
          <a href="{% url 'delete' pk=post.pk %}"> 삭제하기 </a>
        </div>
      
        <!-- <form method="POST" action="/comment/{{ post.id }}">
          {% csrf_token %}
          {{ comment_form.as_p }}
          <input type="submit" value="submit">
        </form> -->
        <table border=" 3">
        {% for comment in post.comments.all %}
          <tr><p> {{ comment.c_writer }}의 댓글 : {{ comment.text }}</p></tr>
        {% endfor %}
      </table>
      </div>
    </div>
  </div>
</section>
{% endfor %}

{% endblock %}

appname/templates/appname/kakao_map.html
{% extends 'appname/base.html' %}
{% load static %}
{% block content %}
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<h1>map API</h1>

//카카오 map api 구현 model feild restaurant_location


<div id="map" style="width:40%;height:350px;"></div>
<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=01115e67f8634b195c8ba68b88d18589&libraries=services"></script>
<script>
     // 마커를 클릭하면 장소명을 표출할 인포윈도우 입니다
     var infowindow = new kakao.maps.InfoWindow({zIndex:1});
     
     var mapContainer = document.getElementById('map'), // 지도를 표시할 div 
         mapOption = {
             center: new kakao.maps.LatLng(37.566826, 126.9786567), // 지도의 중심좌표
             level: 4 // 지도의 확대 레벨
         };  
     
     // 지도를 생성합니다    
     var map = new kakao.maps.Map(mapContainer, mapOption); 
     
     // 장소 검색 객체를 생성합니다
     var ps = new kakao.maps.services.Places(); 
     
     // 키워드로 장소를 검색합니다
     ps.keywordSearch('{{post.restaurant_location}}', placesSearchCB); 
     
     // 키워드 검색 완료 시 호출되는 콜백함수 입니다
     function placesSearchCB (data, status, pagination) {
         if (status === kakao.maps.services.Status.OK) {
     
             // 검색된 장소 위치를 기준으로 지도 범위를 재설정하기위해
             // LatLngBounds 객체에 좌표를 추가합니다
             var bounds = new kakao.maps.LatLngBounds();
     
             for (var i=0; i<data.length; i++) {
                 displayMarker(data[i]);    
                 bounds.extend(new kakao.maps.LatLng(data[i].y, data[i].x));
             }       
     
             // 검색된 장소 위치를 기준으로 지도 범위를 재설정합니다
             map.setBounds(bounds);
         } 
     }
     
     // 지도에 마커를 표시하는 함수입니다
     function displayMarker(place) {
         
         // 마커를 생성하고 지도에 표시합니다
         var marker = new kakao.maps.Marker({
             map: map,
             position: new kakao.maps.LatLng(place.y, place.x) 
         });
     
         // 마커에 클릭이벤트를 등록합니다
         kakao.maps.event.addListener(marker, 'click', function() {
             // 마커를 클릭하면 장소명이 인포윈도우에 표출됩니다
             infowindow.setContent('<div style="padding:5px;font-size:18px;">' + place.place_name + '</div>');
             infowindow.open(map, marker);
         });
     }
     </script>
     <br>
     <h1 style="color: cornflowerblue;">위치 검색 결과 : {{post.restaurant_location}}</h1>
{% endblock %}

appname/templates/appname/main.html
{% extends 'appname/base.html' %}
{% load static %}
{% load calc %}
{% load crispy_forms_tags %}
{% block header %}

{% endblock %}

{% block content %}
<br>
<br>
<br>
<br>
//좌측 상단 가입되어 있는 모든 user객체의 username,profileimage 
<div class="col-10 row-1 justify-content-left" style="position:fixed ; width : 100%;" >
  <div class="col-md-3" >
    <h1> 사용자 </h1>
    <div class="thumbnail" style="border: 0.3em solid lightsteelblue;">
      <p style="font-size: 15px; color: mediumturquoise;">현재 사용자 : {{user.username}}</p>
      {% if user.profileimage %}
      <img src="/media/{{user.profileimage}}" class="img-circle img-rounded"alt="..."width="50%"height="50%" >
      {% else %}
      <img src="/static/appname/img/kakao.png" alt="..."width="50%"height="50%" >
      {% endif %}
      <div class="caption" style="text-align: left;" >
        {% for users in pages %}
        {% if users.profileimage %}
        <p style="font-style: oblique; font-size: medium;"><img src="/media/{{users.profileimage}}" class="img-circle img-rounded" alt="..." style="width: 15%; height: 15%;"> {{users.username}}</p>
        {% else %}
        <p style="font-style: oblique; font-size: medium;"><img  src="/static/appname/img/기본프로필.jpg" class="img-circle img-rounded" alt="..." style="width: 15%; height: 15%;">{{users.username}}</p>
        {% endif %}
        {% endfor %}
       
<br>
        {%if pages.has_previous%}
          <a href="?page=1">1</a>
          <a href="?page={{pages.previous_page_number}}">이 전</a>
        {%endif%}

          <span>{{pages.number}}</span>
          <span>of</span>
          <span>{{pages.paginator.num_pages}}</span>

        {%if pages.has_next%}
          <a href="?page={{pages.next_page_number}}">다음</a>
          <a href="?page={{pages.paginator.num_pages}}">마지막</a>
        {%endif%}
      </div>
    </div>
  </div>
</div>

<div class="container" style="width: 100%;">
  <!-- <h1>{{user.username}}</h1> -->

  {% for post in posts %}
  <br>
  <div class="row h-25 justify-content-center">

    <div class="col-md-5 thumbnail" style="position: relative; ">
      <div class="row align-items-center" style="color: black;">
        <div class="col" id="post_{{post.id}}">
          <br>
          {% if post.writer.profileimage %}
          <h4><img src="{{post.writer.profileimage.url}}" class="img-circle img-rounded" alt="..." width="15%">
            {{ post.writer}} &nbsp; {{post.create_date|time_since}}</h4>

          {% else %}
          <h4 class="glyphicon glyphicon-user">{{ post.writer}} {{post.create_date|time_since}}</h4>
          {% endif %}

         
          <br>
          <br>
          {% if post.image %}
          <img src="{{ post.image.url }}" alt="" width="100%" height="100%">
          {% endif %}
          <p style="font-size: medium;">{{post.content}}</p>
          <span>
            {% for hashtag in post.hashtags.all %}
            <a href="/hashtag/{{ hashtag.name }}">
              #{{ hashtag.name }}
            </a>
            {% endfor %}
          </span>
          <br>
           {% if post.restaurant_location %}
          <a href="{% url 'kakao_map' post.pk %}">{{post.restaurant_location}} 위치 보러가기</a>
            {% else %}
          
          {% endif %}
          <br>
          {% if user == post.writer%}
          <div class="btn-group" style>
            <a href="{% url 'update' post.id %}"><img src="/static/appname/img/update.png" alt="update"
                style="justify-content: left;"></a>
            <a href="{% url 'delete' post.id %}" onclick="return confirm('정말 삭제하시겠습니까?')"><img
                src="/static/appname/img/delete.png" alt="delete"></a>
          </div>
          {% endif %}
          <br>
          <input type="image" class="like" name="{{ post.id }}" src="/static/appname/img/다운로드.png" width="30">
          <p id="count-{{ post.id }}">좋아용 {{ post.like_count }}개</p>

          <br>
          <form action="{% url 'comment' post.id %}" method="POST">
            {% csrf_token %}
            <table>
              {{ comment_form|crispy }}
            </table>
            <input type="submit" value="댓글쓰기" class="btn btn-info" >
          </form>

          {% for comment in post.comments.all %}
          <a class="card-text" href="#"><span class="comment_writer_name">{{comment.c_writer}}</span></a>
          <a class="card-text">{{comment.text}}</a>
          <br>

          <br>
          {% endfor %}

        </div>
      </div>
    </div>
  </div>


  {% endfor %}
  //좋아요 ajax 구현 
  <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
  <script type="text/javascript">
    $(".like").click(function () {
      var pk = $(this).attr('name')
      $.ajax({ // .like 버튼을 클릭하면 <새로고침> 없이 ajax로 서버와 통신하겠다.
        type: "POST", // 데이터를 전송하는 방법을 지정
        url: "{% url 'post_like' %}", // 통신할 url을 지정
        data: { 'pk': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}' }, // 서버로 데이터 전송시 옵션
        dataType: "json", // 서버측에서 전송한 데이터를 어떤 형식의 데이터로서 해석할 것인가를 지정, 없으면 알아서 판단
        // 서버측에서 전송한 Response 데이터 형식 (json)
        // {'likes_count': post.like_count, 'message': message }
        success: function (response) { // 통신 성공시 - 동적으로 좋아요 갯수 변경, 유저 목록 변경
          alert(response.message);
          $("#count-" + pk).html("좋아용 " + response.like_count + "개");
          var users = $("#like-user-" + pk).text();
          if (users.indexOf(response.nickname) != -1) {
            $("#like-user-" + pk).text(users.replace(response.nickname, ""));
          } else {
            $("#like-user-" + pk).text(response.nickname + users);
          }
        },
        error: function (request, status, error) { // 통신 실패시 - 로그인 페이지 리다이렉트
          alert("로그인이 필요합니다.")
          // window.location.replace("/accounts/login/")
          //  alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
        },
      });
    })
    // $(".commentFormm").submit(function () {
    //   var pk = $(this).attr('id');
    //   var params = $(this).serialize();
    //   $.ajax({ 
    //     type: "POST",
    //     url: "/comment/" + pk,
    //     data: params,
    //     success: function (json) {
    //       $("post_" + pk).prepend(data.html);
    //     },
    //     error: function (request, status, error) { // 통신 실패시 - 로그인 페이지 리다이렉트
    //       alert(error);
    //     },
    //   });
    // })

  </script>
</div>

{% endblock %}

appname/templates/appname/signin.html
{% extends 'appname/base.html' %}

{% block header %}
<br>
<br>
<br>
<br>
<br>
<header class="masthead text-center text-white">
    <div class="masthead-content">
      <div class="container">
        <h1 class="masthead-heading mb-0">로그인</h1>
      </div>
    </div>
    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div>
    <div class="bg-circle-4 bg-circle"></div>
  </header>
{% endblock %}

{% block content %}
<form method="POST" action="signin">
    {% csrf_token %}
    {{ signin_form.as_p }}
    <input type="submit" value="submit">
</form>
{% endblock %}

appname/templates/appname/signup.html
{% extends 'appname/base.html' %}

{% block header %}
<header class="masthead text-center text-white">
    <div class="masthead-content">
      <div class="container">
        <h1 class="masthead-heading mb-0">진형준 SNS 회원가입</h1>
      </div>
    </div>
    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div>
    <div class="bg-circle-4 bg-circle"></div>
  </header>
{% endblock %}

{% block content %}

<br>

<br>

<br>

<br>

<br>

<form method="POST"  enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="submit">
</form>
{% endblock %}

appname/templates/appname/update.html
{% extends 'appname/base.html' %}

{% block header %}
<header class="masthead text-center text-white">
  <div class="masthead-content">
    <div class="container">
      <h1 class="masthead-heading mb-0">Jinstagram</h1>
      
      <a href="/create" class="btn btn-primary btn-xl rounded-pill mt-5">Write a Post</a>
    </div>
  </div>
  <div class="bg-circle-1 bg-circle"></div>
  <div class="bg-circle-2 bg-circle"></div>
  <div class="bg-circle-3 bg-circle"></div>
  <div class="bg-circle-4 bg-circle"></div>
</header>
{%  endblock %}
{% block content %}

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table}}
    </table>
    <button type="submit" value="submit" onclick="return confirm('정말 수정할꺼니??')"></button>
</form>

{% endblock %}